# Generated by Django 5.0.6 on 2024-07-12 16:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='date_created',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='reply',
            old_name='date_created',
            new_name='created_at',
        ),
        migrations.AddField(
            model_name='question',
            name='title',
            field=models.CharField(default='Question title here...', max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='reply',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='vote',
            name='vote_type',
            field=models.CharField(choices=[('UPVOTE', 'upvote'), ('DOWNVOTE', 'downvote')], null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='body',
            field=models.TextField(blank=True, default='Question body here...', max_length=500),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='reply',
            name='body',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='vote',
            name='reply',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='questions.reply'),
        ),
        migrations.AlterField(
            model_name='vote',
            name='voted_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='votes', to=settings.AUTH_USER_MODEL),
        ),
    ]
