# Generated by Django 5.0.7 on 2024-07-28 17:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0002_uuidtaggeditem_alter_question_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='questions.question'),
        ),
        migrations.AlterField(
            model_name='vote',
            name='reply',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='questions.reply'),
        ),
    ]
