# Generated by Django 5.0.7 on 2024-07-30 02:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0003_alter_vote_question_alter_vote_reply'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='vote_type',
            field=models.CharField(blank=True, choices=[('UPVOTE', 'upvote'), ('DOWNVOTE', 'downvote')], null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='voted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='question_votes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reply',
            name='vote_type',
            field=models.CharField(blank=True, choices=[('UPVOTE', 'upvote'), ('DOWNVOTE', 'downvote')], null=True),
        ),
        migrations.AddField(
            model_name='reply',
            name='voted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reply_votes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='question',
            name='slug',
            field=models.SlugField(max_length=250, null=True, unique=True),
        ),
        migrations.DeleteModel(
            name='Vote',
        ),
    ]
